table fact_sales
	lineageTag: 97fea3af-b014-4be0-9049-96c172e21178

	measure 'Total sales' = ```
			
			    sum(fact_sales[Amount])
			```
		formatString: 0
		displayFolder: Measures
		lineageTag: 8f560647-4fc6-413e-bca0-a0f5bb85b194

	measure 'Total Boxes' = ```
			
			     sum(fact_sales[Boxes])
			```
		formatString: 0
		displayFolder: Measures
		lineageTag: 100bb315-651e-4ee6-942e-6276b910e4fb

	measure 'Shipment Counts' = ```
			
			    COUNTROWS(fact_sales)
			```
		formatString: 0
		displayFolder: Measures
		lineageTag: fe026742-9319-4d1a-a9fd-14f072a1f16c

	measure 'Low box Shipments count' =
			
			CALCULATE([Shipment Counts],fact_sales[Boxes]<50)
		formatString: 0
		displayFolder: Measures
		lineageTag: 15a77875-6b34-4d2d-90e1-f199b46388e4

	measure LBS% = ```
			
			    DIVIDE([Low box Shipments count],[Shipment Counts])
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Measures
		lineageTag: ce85e4dd-d4f3-4bf8-9a1c-08ac7dc53bee

	measure 'Current MTD' =
			
			TOTALMTD(
			    [Total sales],DATESMTD('fact_sales'[Date]))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 62e09de3-790a-4cbb-82db-e887c1d636d3

	measure 'Current QTD' = TOTALQTD([Total sales],DATESQTD(fact_sales[Date]))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 9739ab71-9af0-4ef7-bef2-ac1e6428a532

	measure 'Current YTD' = ```
			
			 TOTALYTD([Total sales], DATESYTD(fact_sales[Date]))
			```
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 9dc3dfec-fdbf-4ee7-94bf-7de6cfef6ba5

	measure 'Previous MTD' =
			
			CALCULATE([Total sales],
			    PREVIOUSMONTH(DATESMTD(fact_sales[Date])))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 857a7e07-db60-4834-8d81-ce4832a39ed1

	measure 'Previous QTD' =
			
			CALCULATE([Total sales],
			    PREVIOUSQUARTER(DATESMTD(fact_sales[Date])))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 18872870-153a-4f1e-b65b-dee490986a21

	measure 'Previous YTD' =
			
			CALCULATE([Total sales],
			    PREVIOUSYEAR(DATESMTD(fact_sales[Date])))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: c982bf75-6f6c-4fe5-aaeb-02eebe7bf104

	measure 'MOM Growth' =
			
			DIVIDE([Current MTD],[Previous MTD])-1
		formatString: 0%;-0%;0%
		displayFolder: Time Intelligence
		lineageTag: b58ee8a9-671c-4cc4-834d-b82aaa62edb3

	measure 'QOQ Growth' =
			
			DIVIDE([Current QTD],[Previous QTD])-1
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: d02b5ecd-d802-45e5-a09b-cfb138dd0711

	measure 'YOY Growth' =
			
			DIVIDE([Current YTD],[Previous YTD])-1
		formatString: 0%;-0%;0%
		displayFolder: Time Intelligence
		lineageTag: 28678e45-7f8f-4c98-a934-46b696abb659

	column SP_ID
		dataType: string
		lineageTag: 51bc01b2-3831-4e61-a22b-e3094b61b808
		summarizeBy: none
		sourceColumn: SP_ID

		annotation SummarizationSetBy = Automatic

	column Geo_ID
		dataType: string
		lineageTag: b30978d3-8bed-4e41-b5d8-506e2fc64f71
		summarizeBy: none
		sourceColumn: Geo_ID

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		lineageTag: 46780b02-ec1b-4e47-958d-dbf614550243
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 426fb7a4-4076-440b-ac79-e576b576e9c6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 64395ca3-c94b-4a49-9b62-15ebabadb767
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Customers
		dataType: int64
		formatString: 0
		lineageTag: ecfec014-b61f-42c4-a361-0ff7b8e1eba7
		summarizeBy: sum
		sourceColumn: Customers

		annotation SummarizationSetBy = Automatic

	column Boxes
		dataType: int64
		formatString: 0
		lineageTag: 6e9e69c1-d709-432d-912a-fdeb7efa2880
		summarizeBy: sum
		sourceColumn: Boxes

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
				    Source = Sql.Databases("LISHA\SQLEXPRESS"),
				    ac = Source{[Name="ac"]}[Data],
				    dbo_sales = ac{[Schema="dbo",Item="sales"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_sales,{{"Product", "Product_ID"}, {"Sales_Person", "SP_ID"}, {"Geo", "Geo_ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

