table fact_sales
	lineageTag: 97fea3af-b014-4be0-9049-96c172e21178

	measure 'Total sales' = ```
			
			    sum(fact_sales[Amount])
			```
		formatString: 0
		displayFolder: Measures
		lineageTag: 8f560647-4fc6-413e-bca0-a0f5bb85b194

	measure 'Total Boxes' = ```
			
			     sum(fact_sales[Boxes])
			```
		formatString: 0
		displayFolder: Measures
		lineageTag: 100bb315-651e-4ee6-942e-6276b910e4fb

	measure 'Shipment Counts' = ```
			
			    COUNTROWS(fact_sales)
			```
		formatString: 0
		displayFolder: Measures
		lineageTag: fe026742-9319-4d1a-a9fd-14f072a1f16c

	measure 'Low box Shipments count' =
			
			CALCULATE([Shipment Counts],fact_sales[Boxes]<50)
		formatString: 0
		displayFolder: Measures
		lineageTag: 15a77875-6b34-4d2d-90e1-f199b46388e4

	measure LBS% = ```
			
			    DIVIDE([Low box Shipments count],[Shipment Counts])
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Measures
		lineageTag: ce85e4dd-d4f3-4bf8-9a1c-08ac7dc53bee

	measure 'Current MTD' =
			
			TOTALMTD(
			    [Total sales],DATESMTD('fact_sales'[Date]))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 62e09de3-790a-4cbb-82db-e887c1d636d3

	measure 'Current QTD' = TOTALQTD([Total sales],DATESQTD(fact_sales[Date]))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 9739ab71-9af0-4ef7-bef2-ac1e6428a532

	measure 'Current YTD' = ```
			
			 TOTALYTD([Total sales], DATESYTD(fact_sales[Date]))
			```
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 9dc3dfec-fdbf-4ee7-94bf-7de6cfef6ba5

	measure 'Previous MTD' =
			
			CALCULATE([Total sales],
			    PREVIOUSMONTH(DATESMTD(fact_sales[Date])))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 857a7e07-db60-4834-8d81-ce4832a39ed1

	measure 'Previous QTD' =
			
			CALCULATE([Total sales],
			    PREVIOUSQUARTER(DATESMTD(fact_sales[Date])))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 18872870-153a-4f1e-b65b-dee490986a21

	measure 'Previous YTD' =
			
			CALCULATE([Total sales],
			    PREVIOUSYEAR(DATESMTD(fact_sales[Date])))
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: c982bf75-6f6c-4fe5-aaeb-02eebe7bf104

	measure 'MOM Growth' =
			
			DIVIDE([Current MTD],[Previous MTD])-1
		formatString: 0%;-0%;0%
		displayFolder: Time Intelligence
		lineageTag: b58ee8a9-671c-4cc4-834d-b82aaa62edb3

	measure 'QOQ Growth' =
			
			DIVIDE([Current QTD],[Previous QTD])-1
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence
		lineageTag: d02b5ecd-d802-45e5-a09b-cfb138dd0711

	measure 'YOY Growth' =
			
			DIVIDE([Current YTD],[Previous YTD])-1
		formatString: 0%;-0%;0%
		displayFolder: Time Intelligence
		lineageTag: 28678e45-7f8f-4c98-a934-46b696abb659

	measure 'YTD Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Total sales
		lineageTag: f05f02f4-6fac-4d5a-a027-06fe3f843118

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Total sales
		lineageTag: 78fec6f5-6d4f-4a35-a311-bb56b8bfe93d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Total sales
		lineageTag: 880068dc-3b1b-4495-8654-8e541de9cbb5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: 213485bb-7f39-45ae-bbdb-05016edbaff6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Total sales' =
			
			VAR __ValueCurrentPeriod = [Total sales]
			VAR __ValuePreviousPeriod = [PY Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: ad945028-1307-494a-8f58-0d4c8cc2d072

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Total sales' = ```
			
			DIVIDE ( 
			    [YOY Total sales],
			    [PY Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: 60c0d6ec-85ac-40fa-bb0d-7bd1f2ad11e5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: 07eda57c-0c02-462f-9469-cd133b3e1b87

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Total sales' =
			
			VAR __ValueCurrentPeriod = [Total sales]
			VAR __ValuePreviousPeriod = [PQ Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: 289e3513-4af8-4bdd-ba15-4e3f99d0b413

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Total sales' = ```
			
			DIVIDE ( 
			    [QOQ Total sales],
			    [PQ Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: bfa54ccd-e147-40a3-9c2f-e6bcb5923f07

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: 424bf510-d0c8-4077-8f6e-f6b54cd6a2b3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Total sales' =
			
			VAR __ValueCurrentPeriod = [Total sales]
			VAR __ValuePreviousPeriod = [PM Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: 3c41b097-dbdc-47f7-a063-7405a6ee9987

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Total sales' = ```
			
			DIVIDE ( 
			    [MOM Total sales],
			    [PM Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Total sales
		lineageTag: ecf4106f-0809-44f7-a79e-2ac11aea3314

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Total sales],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: 7c9b16e4-723c-496b-9afa-2feaf8a44d91

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Total sales' =
			
			VAR __ValueCurrentPeriod = [YTD Total sales]
			VAR __ValuePreviousPeriod = [PYTD Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: cfcc07d1-894d-4117-842d-f7a9a4e12231

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Total sales' = ```
			
			DIVIDE ( 
			    [YOYTD Total sales],
			    [PYTD Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: a1e2a791-20b5-4d05-9ec0-88abd6d03461

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Total sales],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: 197802a6-fe3d-43cf-8d38-5b19ee4b47fa

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Total sales' =
			
			VAR __ValueCurrentPeriod = [QTD Total sales]
			VAR __ValuePreviousPeriod = [PQTD Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: cf14b125-d2c4-46cd-80bd-13a90d6193bf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Total sales' = ```
			
			DIVIDE ( 
			    [QOQTD Total sales],
			    [PQTD Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: df457664-ffc7-47c9-ae7f-95301cd7c5ea

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Total sales],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: 947ce868-edeb-41fe-a55b-f7d21406fec8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Total sales' =
			
			VAR __ValueCurrentPeriod = [MTD Total sales]
			VAR __ValuePreviousPeriod = [PMTD Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: 6ba8d98b-f0b7-4636-96ac-b0cb18a8bfec

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Total sales' = ```
			
			DIVIDE ( 
			    [MOMTD Total sales],
			    [PMTD Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Total sales
		lineageTag: 09482ff9-a129-4541-a3d2-1d2bb7c473ef

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: 608d8ae3-8ce6-4d07-9e2d-b55ed96fa06e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Total sales' =
			
			VAR __ValueCurrentPeriod = [YTD Total sales]
			VAR __ValuePreviousPeriod = [PYC Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: e460c35d-f4d2-4bf9-bda4-64a267ac71a1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Total sales' = ```
			
			DIVIDE ( 
			    [YTDOPY Total sales],
			    [PYC Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: dafa29ab-2f45-48af-a86e-0d6ae01fb584

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: c61dffb3-d441-4231-863f-b7b6943af129

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Total sales' =
			
			VAR __ValueCurrentPeriod = [QTD Total sales]
			VAR __ValuePreviousPeriod = [PQC Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: 31c9e99c-d0df-43e4-b918-7b17d877c9b1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Total sales' = ```
			
			DIVIDE ( 
			    [QTDOPQ Total sales],
			    [PQC Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: 6fc186d1-b92e-4f09-9e46-80db7787462e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: ddf1862e-68fa-4622-bd4b-fba7f988a523

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Total sales' =
			
			VAR __ValueCurrentPeriod = [MTD Total sales]
			VAR __ValuePreviousPeriod = [PMC Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: 8b86bb4d-882d-4ae5-a1df-4e057cd35d2e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Total sales' = ```
			
			DIVIDE ( 
			    [MTDOPM Total sales],
			    [PMC Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Total sales
		lineageTag: d3f9c2b1-d395-4e1e-acc7-7fd55d0bc65a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total sales],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Total sales
		lineageTag: 65467658-936f-4dd0-8acf-1eabb5c3f74b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Total sales' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Total sales],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Total sales
		lineageTag: cea46c38-2d7f-455e-b070-2687829b89df

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Total sales' =
			
			VAR __ValueCurrentPeriod = [MAT Total sales]
			VAR __ValuePreviousPeriod = [PYMAT Total sales]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Total sales
		lineageTag: 473b4946-b595-47d1-93ed-c2a4c3009cec

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Total sales' = ```
			
			DIVIDE ( 
			    [MATG Total sales],
			    [PYMAT Total sales]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\Total sales
		lineageTag: 637eb3f1-abd5-4db6-9f55-901214309a7a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Total Boxes
		lineageTag: 269bea45-79e9-4383-8a85-e5a6f307cbb9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Total Boxes
		lineageTag: 6f02ecba-46ed-49bc-84ab-47dcecded600

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Total Boxes
		lineageTag: ca18b0fe-78fb-4bd6-9f2c-7f3a7abbe94f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: 00c4e0e0-bf98-4984-ad40-cd2be7cccabf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Total Boxes' =
			
			VAR __ValueCurrentPeriod = [Total Boxes]
			VAR __ValuePreviousPeriod = [PY Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: 253be56c-8c7b-4878-b549-59754429a57d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Total Boxes' = ```
			
			DIVIDE ( 
			    [YOY Total Boxes],
			    [PY Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: 74656150-b7cd-4a86-bee7-e5d0d1714aa3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: df055610-a035-4cc1-8ab3-2ae6b16c981f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Total Boxes' =
			
			VAR __ValueCurrentPeriod = [Total Boxes]
			VAR __ValuePreviousPeriod = [PQ Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: 821040b0-e5c6-4e1f-be5a-7aa8e5e2e3b9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Total Boxes' = ```
			
			DIVIDE ( 
			    [QOQ Total Boxes],
			    [PQ Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: 908b1b17-2bf9-4abb-a9ca-625acb3e6f5a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: b983ab40-13b6-4ca1-bdcc-6b9b4dea6d4e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Total Boxes' =
			
			VAR __ValueCurrentPeriod = [Total Boxes]
			VAR __ValuePreviousPeriod = [PM Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: bef8a5e6-5578-44f4-8215-c5da573b8ad0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Total Boxes' = ```
			
			DIVIDE ( 
			    [MOM Total Boxes],
			    [PM Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Total Boxes
		lineageTag: aaee822d-1248-4ad1-860c-d6a5fe897639

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Total Boxes],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: 7bab6ad2-1189-4464-bcba-39ee64a6d109

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Total Boxes' =
			
			VAR __ValueCurrentPeriod = [YTD Total Boxes]
			VAR __ValuePreviousPeriod = [PYTD Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: 1884e15c-08c7-4b07-904e-b978737d55c3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Total Boxes' = ```
			
			DIVIDE ( 
			    [YOYTD Total Boxes],
			    [PYTD Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: ac716ddb-3b6a-4a16-9500-83b53b89b14e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Total Boxes],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: 1cfee754-ae0e-41ed-97c7-2896aa4ce606

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Total Boxes' =
			
			VAR __ValueCurrentPeriod = [QTD Total Boxes]
			VAR __ValuePreviousPeriod = [PQTD Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: 84e6ccc9-4d81-4886-bce4-9e4f081fd320

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Total Boxes' = ```
			
			DIVIDE ( 
			    [QOQTD Total Boxes],
			    [PQTD Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: cd392c53-3054-4844-a7a7-46f3dbe27617

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Total Boxes],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: bef21db2-05d9-4fed-ad67-4111cbc38566

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Total Boxes' =
			
			VAR __ValueCurrentPeriod = [MTD Total Boxes]
			VAR __ValuePreviousPeriod = [PMTD Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: f6a3edae-6ffb-445b-bd4a-24c8f1764fe9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Total Boxes' = ```
			
			DIVIDE ( 
			    [MOMTD Total Boxes],
			    [PMTD Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Total Boxes
		lineageTag: 7a88f13c-af21-428a-a64f-1f0cfe8d8037

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: f223ae21-996a-4c1a-82f6-ec463c99ea67

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Total Boxes' =
			
			VAR __ValueCurrentPeriod = [YTD Total Boxes]
			VAR __ValuePreviousPeriod = [PYC Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: 836922e9-22a8-4ae9-a599-f371e4a5316f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Total Boxes' = ```
			
			DIVIDE ( 
			    [YTDOPY Total Boxes],
			    [PYC Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: efc2b67e-a476-4c5a-9188-8e8ef3502344

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: 5dcedd35-8806-41c4-aabb-8c9bacfceaf5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Total Boxes' =
			
			VAR __ValueCurrentPeriod = [QTD Total Boxes]
			VAR __ValuePreviousPeriod = [PQC Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: cd8947ef-4884-43e6-8d7e-3ddf526cfc77

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Total Boxes' = ```
			
			DIVIDE ( 
			    [QTDOPQ Total Boxes],
			    [PQC Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: e3a73536-3a9e-44ea-bff4-6c0f9e1613a3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: 6e8f2e31-33f5-4350-bbd4-157f72485ced

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Total Boxes' =
			
			VAR __ValueCurrentPeriod = [MTD Total Boxes]
			VAR __ValuePreviousPeriod = [PMC Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: 98384f15-7361-4392-8e71-5b9f04d4a076

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Total Boxes' = ```
			
			DIVIDE ( 
			    [MTDOPM Total Boxes],
			    [PMC Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Total Boxes
		lineageTag: 4b272201-6ad0-4a27-acf7-409f1e050346

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Total Boxes],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Total Boxes
		lineageTag: 1ea941f4-775d-4a77-a69b-1738db478088

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Total Boxes' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Total Boxes],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Total Boxes
		lineageTag: f40282ad-5c86-44ca-a96d-3db5e44e968f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Total Boxes' =
			
			VAR __ValueCurrentPeriod = [MAT Total Boxes]
			VAR __ValuePreviousPeriod = [PYMAT Total Boxes]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Total Boxes
		lineageTag: 903017e8-2f4d-4eb9-b10d-da43c1aa74f9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Total Boxes' = ```
			
			DIVIDE ( 
			    [MATG Total Boxes],
			    [PYMAT Total Boxes]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\Total Boxes
		lineageTag: 9a1927bf-1b8e-4961-942f-50789b389a64

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Shipment Counts
		lineageTag: 1eebe2ad-37ce-47d8-8deb-7ef08fb13753

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Shipment Counts
		lineageTag: 501a4f1c-a595-48df-83c8-4c02735fb3e4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Shipment Counts
		lineageTag: 513eb276-14ca-44c8-96c9-7b770a0c5956

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: d3aeb645-5cf6-43c2-8805-c314dd123e07

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [Shipment Counts]
			VAR __ValuePreviousPeriod = [PY Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: a7a8e6c3-6bbc-4922-847b-8715b74003a1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Shipment Counts' = ```
			
			DIVIDE ( 
			    [YOY Shipment Counts],
			    [PY Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: 49c8328f-b017-4c59-9805-122e18437040

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: c529de71-0b1f-493d-a4d2-293fd8c226ad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [Shipment Counts]
			VAR __ValuePreviousPeriod = [PQ Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: 128ea2b4-0b97-4b2a-9c5b-163656e9d92b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Shipment Counts' = ```
			
			DIVIDE ( 
			    [QOQ Shipment Counts],
			    [PQ Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: 764ab8ae-289e-47f4-988a-3ab84523f3a9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: 668ae2ee-6020-48cd-83a2-c147bbca04fb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [Shipment Counts]
			VAR __ValuePreviousPeriod = [PM Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: 77d98cd3-6a6e-4071-a847-63f88ee43f2c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Shipment Counts' = ```
			
			DIVIDE ( 
			    [MOM Shipment Counts],
			    [PM Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Shipment Counts
		lineageTag: a011da6f-7323-4f3c-92ab-e907b2a9b16e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Shipment Counts],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: a1241257-147f-4e09-b285-8822321edc6d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [YTD Shipment Counts]
			VAR __ValuePreviousPeriod = [PYTD Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: a3e38226-4f2f-4b72-87ee-a2137ead01c8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Shipment Counts' = ```
			
			DIVIDE ( 
			    [YOYTD Shipment Counts],
			    [PYTD Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: a00fdb2e-376e-42ea-ba50-24ba957bbd3e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Shipment Counts],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: f02dbe31-bc4b-42f7-9697-d840a878b3f7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [QTD Shipment Counts]
			VAR __ValuePreviousPeriod = [PQTD Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: dbf3d110-97fb-4960-9d2f-6858d75408cf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Shipment Counts' = ```
			
			DIVIDE ( 
			    [QOQTD Shipment Counts],
			    [PQTD Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: eaf67baa-7130-4377-8e3c-f9bf72ff14b7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Shipment Counts],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: 17808a03-88da-40a4-9acc-400acca4f3a8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [MTD Shipment Counts]
			VAR __ValuePreviousPeriod = [PMTD Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: 33e38b94-3371-4274-8f52-296d91bdff3b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Shipment Counts' = ```
			
			DIVIDE ( 
			    [MOMTD Shipment Counts],
			    [PMTD Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Shipment Counts
		lineageTag: 8cb72039-e134-4272-b7ab-ce0aedd3b9cd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: d2ba77e7-be8c-499a-ada9-e2f6361f74dd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [YTD Shipment Counts]
			VAR __ValuePreviousPeriod = [PYC Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: aa46189a-ea70-4baa-b8e0-a55ede0df5ab

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Shipment Counts' = ```
			
			DIVIDE ( 
			    [YTDOPY Shipment Counts],
			    [PYC Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: 74ba4a55-2851-403c-8449-3187534513bd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: 9d3dd134-be2f-429f-8551-4f5d100c03ca

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [QTD Shipment Counts]
			VAR __ValuePreviousPeriod = [PQC Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: af467e8a-db6a-455d-98e5-293f4cd56a7f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Shipment Counts' = ```
			
			DIVIDE ( 
			    [QTDOPQ Shipment Counts],
			    [PQC Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: 22bd6c23-896a-4219-afcb-dbfa6fa871e6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: 09777a3e-0b85-4064-ae5e-d30824761b0f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [MTD Shipment Counts]
			VAR __ValuePreviousPeriod = [PMC Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: 140daf7f-d4a6-4f1f-9ba1-401a14e48185

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Shipment Counts' = ```
			
			DIVIDE ( 
			    [MTDOPM Shipment Counts],
			    [PMC Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Shipment Counts
		lineageTag: 123c449f-40e6-449a-b2fa-e2d02f19caa3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Shipment Counts],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Shipment Counts
		lineageTag: fa023361-98b0-4326-9168-fe9bca426003

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Shipment Counts' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Shipment Counts],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Shipment Counts
		lineageTag: f6ac4006-5898-4c38-95d5-1d816bbefdc8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Shipment Counts' =
			
			VAR __ValueCurrentPeriod = [MAT Shipment Counts]
			VAR __ValuePreviousPeriod = [PYMAT Shipment Counts]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Shipment Counts
		lineageTag: 2074f835-19af-437e-b55b-3c7465b317c1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Shipment Counts' = ```
			
			DIVIDE ( 
			    [MATG Shipment Counts],
			    [PYMAT Shipment Counts]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\Shipment Counts
		lineageTag: e69cf67d-2ef1-4695-8a61-3dfa3a71c25e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Low box Shipments count
		lineageTag: 756ccd4f-d33f-4711-85d1-4c86a9f1f178

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Low box Shipments count
		lineageTag: 2d44bc6b-c1b2-4289-a742-b24b9bdb5a1f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Measures\Low box Shipments count
		lineageTag: ddda6e84-99ae-4d9a-8f69-9d41a9000625

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 74e549ab-5790-4d12-a331-cc1dfb8c2014

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [Low box Shipments count]
			VAR __ValuePreviousPeriod = [PY Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 5fab0215-abde-4f60-84f1-d2e2e2f4c432

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [YOY Low box Shipments count],
			    [PY Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 3941b064-91de-47a2-af31-db2ee86d1e45

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 4bbf6ef8-10f2-4c0a-a5dd-8a3643fb64b1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [Low box Shipments count]
			VAR __ValuePreviousPeriod = [PQ Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 710b732f-b51e-4319-ab21-65a83db5f188

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [QOQ Low box Shipments count],
			    [PQ Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 3c3e5c23-cd3a-4a73-abd1-b66139872e73

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 3ad45f9a-6a0a-4d46-a9d2-dd4358c61d20

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [Low box Shipments count]
			VAR __ValuePreviousPeriod = [PM Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: d49c8635-a5c1-4c4d-94d9-bde71511ae35

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [MOM Low box Shipments count],
			    [PM Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\Low box Shipments count
		lineageTag: 6aa2ccfb-93cf-44b8-a8a4-f34c20a58563

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Low box Shipments count],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: b8899bbe-10e0-4432-8f4c-6581510244c6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [YTD Low box Shipments count]
			VAR __ValuePreviousPeriod = [PYTD Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: 26344f1a-92b3-4ee1-a705-99051ef0ca24

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [YOYTD Low box Shipments count],
			    [PYTD Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: 10b116e8-4c84-43d2-939a-88bb7f6a1ec9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Low box Shipments count],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: 7ffc1c6b-9f67-4ef3-9787-69e8acf8438b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [QTD Low box Shipments count]
			VAR __ValuePreviousPeriod = [PQTD Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: 23deb21a-9d06-4f4c-ac33-81e3772c07e9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [QOQTD Low box Shipments count],
			    [PQTD Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: 4646130a-291f-4897-a7e2-75b8db26288b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Low box Shipments count],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: b6e8b46c-c59b-40de-bcb1-a3916d187253

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [MTD Low box Shipments count]
			VAR __ValuePreviousPeriod = [PMTD Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: c771c1a8-0aca-4b9e-bf06-130b272485a9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [MOMTD Low box Shipments count],
			    [PMTD Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\Low box Shipments count
		lineageTag: 5e132ce5-9600-453c-8bdb-168e7295780e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: 430c15fb-8e0f-4fdc-a12c-094fba5aca67

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [YTD Low box Shipments count]
			VAR __ValuePreviousPeriod = [PYC Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: 0b0e0d68-0840-4197-8f6f-bfe03490cd69

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [YTDOPY Low box Shipments count],
			    [PYC Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: 1905aa25-e8be-4986-ab3a-341054a20b79

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: f61f3e65-8cbb-4e75-b83c-f5f4043b7100

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [QTD Low box Shipments count]
			VAR __ValuePreviousPeriod = [PQC Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: abd8ce43-d362-4c02-809d-f39e07d00b93

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [QTDOPQ Low box Shipments count],
			    [PQC Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: ace8c2d6-e16f-46c8-9f9c-1ead68623ccb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: c771d9aa-5cc2-4350-ae94-c4b5e067a333

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [MTD Low box Shipments count]
			VAR __ValuePreviousPeriod = [PMC Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: 51c8a22a-de86-488a-b493-fda3fad32180

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [MTDOPM Low box Shipments count],
			    [PMC Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\Low box Shipments count
		lineageTag: e62dab53-2d06-497a-b68d-59aeebab1ba0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Low box Shipments count],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Low box Shipments count
		lineageTag: 1bbf3aa7-622b-411d-aead-006561e7af03

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Low box Shipments count' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Low box Shipments count],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Low box Shipments count
		lineageTag: bf0e8724-f38e-4172-9d2a-6c3e6649efb0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Low box Shipments count' =
			
			VAR __ValueCurrentPeriod = [MAT Low box Shipments count]
			VAR __ValuePreviousPeriod = [PYMAT Low box Shipments count]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Measures\Low box Shipments count
		lineageTag: af33043b-543a-4146-bc36-9a5de22139c7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Low box Shipments count' = ```
			
			DIVIDE ( 
			    [MATG Low box Shipments count],
			    [PYMAT Low box Shipments count]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\Low box Shipments count
		lineageTag: a3cc0183-afcf-43b4-ace3-bfb92e592e18

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Measures\LBS%
		lineageTag: f79407d2-aec7-47b3-b47f-cffd29a61bb0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Measures\LBS%
		lineageTag: 585086e8-07c7-445a-9b66-b77b4e899677

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Measures\LBS%
		lineageTag: 466a7836-d932-4f03-9ea4-77626764d974

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: 49f8b7e7-6ffa-466e-8a81-40f6cf22daee

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY LBS%' =
			
			VAR __ValueCurrentPeriod = [LBS%]
			VAR __ValuePreviousPeriod = [PY LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: 05a77339-e43d-427f-a9c1-b77236a8057a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % LBS%' = ```
			
			DIVIDE ( 
			    [YOY LBS%],
			    [PY LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: 936dd99f-189c-4da7-9f85-6d3ec71f9203

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: 55f26f5f-e8c9-46a0-b59c-104863774057

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ LBS%' =
			
			VAR __ValueCurrentPeriod = [LBS%]
			VAR __ValuePreviousPeriod = [PQ LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: a669ece4-69e2-4358-be02-2ceb638a9aad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % LBS%' = ```
			
			DIVIDE ( 
			    [QOQ LBS%],
			    [PQ LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: 4addc727-1cd5-45d2-bb6d-b35aace79239

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: 510609ab-8c97-448a-bedb-a7b5f5001152

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM LBS%' =
			
			VAR __ValueCurrentPeriod = [LBS%]
			VAR __ValuePreviousPeriod = [PM LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: e800cb78-d020-4dc7-a3f4-e62fb385597e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % LBS%' = ```
			
			DIVIDE ( 
			    [MOM LBS%],
			    [PM LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Measures\LBS%
		lineageTag: 06a88743-7cc7-4af8-9eaf-6bba04dad94e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD LBS%],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: 16877f5e-a1d5-459f-89c4-d095f88f351b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD LBS%' =
			
			VAR __ValueCurrentPeriod = [YTD LBS%]
			VAR __ValuePreviousPeriod = [PYTD LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: 2f04f349-8ce0-4836-a2ac-4e826be028ac

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % LBS%' = ```
			
			DIVIDE ( 
			    [YOYTD LBS%],
			    [PYTD LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: f7803397-bbbb-4d25-9c0a-71889fdae7b5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD LBS%],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: cf39a65b-9622-4f76-ab86-0873402f3a4f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD LBS%' =
			
			VAR __ValueCurrentPeriod = [QTD LBS%]
			VAR __ValuePreviousPeriod = [PQTD LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: 3af0cc75-70ad-4567-8a6f-a297a109776b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % LBS%' = ```
			
			DIVIDE ( 
			    [QOQTD LBS%],
			    [PQTD LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: 0c2a0ccb-6795-4cc4-b250-00299d7782c5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD LBS%],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: 3cd4b1ef-26f0-4a9d-93f1-dd0a97f9676c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD LBS%' =
			
			VAR __ValueCurrentPeriod = [MTD LBS%]
			VAR __ValuePreviousPeriod = [PMTD LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: 0ed6bf56-5918-434a-9de9-5cf529a921ee

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % LBS%' = ```
			
			DIVIDE ( 
			    [MOMTD LBS%],
			    [PMTD LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Measures\LBS%
		lineageTag: d870b6ac-1cea-4b67-9464-88d238c3b9eb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: f8433193-37d3-4b38-861e-9272a1b0c3a7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY LBS%' =
			
			VAR __ValueCurrentPeriod = [YTD LBS%]
			VAR __ValuePreviousPeriod = [PYC LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: 5f878fc9-c37a-4cd2-8e7d-16973f602a29

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % LBS%' = ```
			
			DIVIDE ( 
			    [YTDOPY LBS%],
			    [PYC LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: 66ee9583-c462-40b6-bc28-d13b1aab763e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: b5cf82af-5c61-428e-b41e-adb75c073f0b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ LBS%' =
			
			VAR __ValueCurrentPeriod = [QTD LBS%]
			VAR __ValuePreviousPeriod = [PQC LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: d2d1f97e-5684-43ba-8614-4a1589816ab3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % LBS%' = ```
			
			DIVIDE ( 
			    [QTDOPQ LBS%],
			    [PQC LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: 6f158f67-367c-4839-bd9d-726a63806580

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: fab293d7-8f51-400c-8311-90563754a366

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM LBS%' =
			
			VAR __ValueCurrentPeriod = [MTD LBS%]
			VAR __ValuePreviousPeriod = [PMC LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: e1eb8a66-41fa-44f5-80e8-c04d0b29ca19

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % LBS%' = ```
			
			DIVIDE ( 
			    [MTDOPM LBS%],
			    [PMC LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Measures\LBS%
		lineageTag: e571d517-a834-435e-99c2-e70064f1e056

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [LBS%],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\LBS%
		lineageTag: e196de13-c9bf-4e59-b775-33ac615115ea

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT LBS%' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT LBS%],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\LBS%
		lineageTag: 538bc8b3-2168-4544-8e93-40d26e7f45c4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG LBS%' =
			
			VAR __ValueCurrentPeriod = [MAT LBS%]
			VAR __ValuePreviousPeriod = [PYMAT LBS%]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\LBS%
		lineageTag: bcd879bd-6082-4cfa-9dea-27bfea4c29df

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % LBS%' = ```
			
			DIVIDE ( 
			    [MATG LBS%],
			    [PYMAT LBS%]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Measures\LBS%
		lineageTag: 492ac07b-7991-4efe-99b4-12da4ee9dfcd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current MTD
		lineageTag: c227f0e2-48da-40c8-a67d-fd2d2615c549

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current MTD
		lineageTag: 41836433-102b-450f-9147-403c7040b425

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current MTD
		lineageTag: 28cc16c4-52d3-4801-ab66-dc860adaf20b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: dfbe918d-0c78-4977-89a8-111307b3e574

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Current MTD' =
			
			VAR __ValueCurrentPeriod = [Current MTD]
			VAR __ValuePreviousPeriod = [PY Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: 66170da5-7d16-414a-a6f2-66ac4947c0bd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Current MTD' = ```
			
			DIVIDE ( 
			    [YOY Current MTD],
			    [PY Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: ccca925a-b10a-4cd1-9bb9-d333d9f6f6db

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: 04be363a-c305-48ee-a5d1-579a461274a6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Current MTD' =
			
			VAR __ValueCurrentPeriod = [Current MTD]
			VAR __ValuePreviousPeriod = [PQ Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: cf5d718f-e9f8-4709-8fc9-1506e85c4d4b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Current MTD' = ```
			
			DIVIDE ( 
			    [QOQ Current MTD],
			    [PQ Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: ab93b6c2-0746-4bcc-8c05-76905a700ab2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: b2f993c0-7edf-460d-9760-71c9945bbd5c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Current MTD' =
			
			VAR __ValueCurrentPeriod = [Current MTD]
			VAR __ValuePreviousPeriod = [PM Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: 011100a4-e021-4c78-bb10-098496a9d17e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Current MTD' = ```
			
			DIVIDE ( 
			    [MOM Current MTD],
			    [PM Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current MTD
		lineageTag: 8f8b66e1-6a6b-4966-9010-26262fc6c456

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Current MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: b4e7b932-eb37-4554-a26c-805f81a0c138

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Current MTD' =
			
			VAR __ValueCurrentPeriod = [YTD Current MTD]
			VAR __ValuePreviousPeriod = [PYTD Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: c1682afa-a7e9-412d-8e30-00d7f9dd3beb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Current MTD' = ```
			
			DIVIDE ( 
			    [YOYTD Current MTD],
			    [PYTD Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: 36f2ccd1-12f2-4524-9417-94183d75556d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Current MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: 0b2990fe-0b87-4816-8dcc-7ff5207bfea5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Current MTD' =
			
			VAR __ValueCurrentPeriod = [QTD Current MTD]
			VAR __ValuePreviousPeriod = [PQTD Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: e4d40402-57a9-453b-ad80-14f7c64fe1d2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Current MTD' = ```
			
			DIVIDE ( 
			    [QOQTD Current MTD],
			    [PQTD Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: f2f91576-08a3-4c81-9120-6b29aec4d12a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Current MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: 829514a1-a10a-4da6-aba8-d5fd1fd9cb1a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Current MTD' =
			
			VAR __ValueCurrentPeriod = [MTD Current MTD]
			VAR __ValuePreviousPeriod = [PMTD Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: 785a2c2c-4068-420f-a87d-80bc14c9301b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Current MTD' = ```
			
			DIVIDE ( 
			    [MOMTD Current MTD],
			    [PMTD Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current MTD
		lineageTag: e23b3d58-8a3f-4e57-9d8d-689187e96825

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 64dc8a54-6f84-4a06-96ed-abde149ccfe2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Current MTD' =
			
			VAR __ValueCurrentPeriod = [YTD Current MTD]
			VAR __ValuePreviousPeriod = [PYC Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 5cd10651-71ac-4763-b2db-573342b3d731

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Current MTD' = ```
			
			DIVIDE ( 
			    [YTDOPY Current MTD],
			    [PYC Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 0f3d6118-2ed9-4ae9-a5a6-a936133d218c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 4310ca4c-2510-4d84-b0df-ceb538df3430

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Current MTD' =
			
			VAR __ValueCurrentPeriod = [QTD Current MTD]
			VAR __ValuePreviousPeriod = [PQC Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 1159ec1c-c9ff-4048-a791-45f0adb76c1a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Current MTD' = ```
			
			DIVIDE ( 
			    [QTDOPQ Current MTD],
			    [PQC Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 5aff2e18-cfc9-4a90-b15e-5fe6e18754cd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 7dd0165c-e725-40ba-97d6-d7eaa1eb429e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Current MTD' =
			
			VAR __ValueCurrentPeriod = [MTD Current MTD]
			VAR __ValuePreviousPeriod = [PMC Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: b7cbe2aa-407d-41c2-bf63-5ecb33e1980c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Current MTD' = ```
			
			DIVIDE ( 
			    [MTDOPM Current MTD],
			    [PMC Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current MTD
		lineageTag: 3d5b0eb9-ab4c-4b8d-ba29-e77373d7e9c7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current MTD],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current MTD
		lineageTag: e6703b97-aaff-4cdf-8c31-e607508a839f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Current MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Current MTD],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current MTD
		lineageTag: 44e68833-707d-4317-b5d5-e70516c4a418

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Current MTD' =
			
			VAR __ValueCurrentPeriod = [MAT Current MTD]
			VAR __ValuePreviousPeriod = [PYMAT Current MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current MTD
		lineageTag: 41d5b009-1da8-4dd0-bd1d-1547357dbac5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Current MTD' = ```
			
			DIVIDE ( 
			    [MATG Current MTD],
			    [PYMAT Current MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current MTD
		lineageTag: 62a036b5-fec8-46a6-af00-e7dea374fc7b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current QTD
		lineageTag: 54a4abdc-eeee-431c-b39b-a0cd788a9332

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current QTD
		lineageTag: 856544f7-9289-4c5c-a942-f6c0a1feae32

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current QTD
		lineageTag: 939244aa-92d9-48ae-b49b-ec711a7678dd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: ddc2c010-cbf3-48aa-99ba-4cc5aa764378

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Current QTD' =
			
			VAR __ValueCurrentPeriod = [Current QTD]
			VAR __ValuePreviousPeriod = [PY Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: 7ab2c11d-f753-4b77-b5e2-991fd85cbd5b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Current QTD' = ```
			
			DIVIDE ( 
			    [YOY Current QTD],
			    [PY Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: f1425e44-ecca-4466-97b3-7f0c235f4e69

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: b461ab3c-70d9-4672-bc62-7046265453fe

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Current QTD' =
			
			VAR __ValueCurrentPeriod = [Current QTD]
			VAR __ValuePreviousPeriod = [PQ Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: bbcc611c-17d6-4df1-ad04-403d076cb6a3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Current QTD' = ```
			
			DIVIDE ( 
			    [QOQ Current QTD],
			    [PQ Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: 83c65f12-64f9-40f2-9fb1-13a02e7d0250

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: 2ab34cc8-fd14-4932-9607-76e5cb9692d7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Current QTD' =
			
			VAR __ValueCurrentPeriod = [Current QTD]
			VAR __ValuePreviousPeriod = [PM Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: 6aefbf0e-a710-4cba-a5d1-6f7f8edfab94

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Current QTD' = ```
			
			DIVIDE ( 
			    [MOM Current QTD],
			    [PM Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current QTD
		lineageTag: 6bd5cce9-637a-49ac-9eca-7af42c73a0a3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Current QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: f851132c-2b5f-4331-94d0-317d4e5c2bf7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Current QTD' =
			
			VAR __ValueCurrentPeriod = [YTD Current QTD]
			VAR __ValuePreviousPeriod = [PYTD Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: 530d7550-762f-42f1-b50e-22e22bdb0270

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Current QTD' = ```
			
			DIVIDE ( 
			    [YOYTD Current QTD],
			    [PYTD Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: 5a532e44-3e34-4091-8d1b-fd4e0115ba0c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Current QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: 3d3cdac2-4fea-4640-9a78-d5c45e1092d0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Current QTD' =
			
			VAR __ValueCurrentPeriod = [QTD Current QTD]
			VAR __ValuePreviousPeriod = [PQTD Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: 20d3b505-6a0f-4118-9259-e3c0f8576864

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Current QTD' = ```
			
			DIVIDE ( 
			    [QOQTD Current QTD],
			    [PQTD Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: 21317f43-0e0e-4eb5-a865-9983f0c724ee

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Current QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: b47146f7-a090-43f8-a695-e8209f21b89e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Current QTD' =
			
			VAR __ValueCurrentPeriod = [MTD Current QTD]
			VAR __ValuePreviousPeriod = [PMTD Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: a9033ee6-0985-4876-84b5-4b2ca7ba0568

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Current QTD' = ```
			
			DIVIDE ( 
			    [MOMTD Current QTD],
			    [PMTD Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current QTD
		lineageTag: 6b263c89-ee45-41b2-a12b-d204254701d8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: 3926ecbc-8538-43f1-810c-0d090c003fbb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Current QTD' =
			
			VAR __ValueCurrentPeriod = [YTD Current QTD]
			VAR __ValuePreviousPeriod = [PYC Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: 7cd15d16-aed7-44ea-a813-03aa3665d2c6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Current QTD' = ```
			
			DIVIDE ( 
			    [YTDOPY Current QTD],
			    [PYC Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: 624fc14c-631a-45ba-a222-09efd250df74

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: 4192099e-d1a4-49ab-9310-565813a0784a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Current QTD' =
			
			VAR __ValueCurrentPeriod = [QTD Current QTD]
			VAR __ValuePreviousPeriod = [PQC Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: e4194313-3f3e-4409-bd3c-89e4c687f380

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Current QTD' = ```
			
			DIVIDE ( 
			    [QTDOPQ Current QTD],
			    [PQC Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: b1ac0eba-6d24-43d9-983f-42af742b2838

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: 24bced82-6a34-4222-8bb6-1880af5fdc5a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Current QTD' =
			
			VAR __ValueCurrentPeriod = [MTD Current QTD]
			VAR __ValuePreviousPeriod = [PMC Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: 77890658-6eb2-41e1-8caf-33620ec5ba63

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Current QTD' = ```
			
			DIVIDE ( 
			    [MTDOPM Current QTD],
			    [PMC Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current QTD
		lineageTag: 14e9ea0a-33d2-4230-91d5-27c8b3dca0ea

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current QTD],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current QTD
		lineageTag: 4d571ff2-12fd-4a7b-be06-406d1c26a18f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Current QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Current QTD],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current QTD
		lineageTag: d4c4dc9a-38e0-4f73-bcc8-b90481dbcb53

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Current QTD' =
			
			VAR __ValueCurrentPeriod = [MAT Current QTD]
			VAR __ValuePreviousPeriod = [PYMAT Current QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current QTD
		lineageTag: a607b740-e5fc-43f5-a530-f1b6c4fd105f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Current QTD' = ```
			
			DIVIDE ( 
			    [MATG Current QTD],
			    [PYMAT Current QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current QTD
		lineageTag: 2124493c-901b-4a97-b628-8790bf55cb16

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current YTD
		lineageTag: 0d345b8b-f7f1-4d65-af0c-8011574ac54b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current YTD
		lineageTag: e3a8dd92-b033-4be0-9212-992bfc2b66ed

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Current YTD
		lineageTag: 926378c4-b2fa-4e60-acaf-553d5e450e4f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: 17f55ffd-6641-4a7e-b441-e60795afed4c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Current YTD' =
			
			VAR __ValueCurrentPeriod = [Current YTD]
			VAR __ValuePreviousPeriod = [PY Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: c524a4f5-9aaf-4136-82a0-7cbd37d50116

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Current YTD' = ```
			
			DIVIDE ( 
			    [YOY Current YTD],
			    [PY Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: b7be9618-49a1-474e-9653-3caf2ee947f5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: 12f47bea-bd1a-43c2-a46a-a1abdebfeab9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Current YTD' =
			
			VAR __ValueCurrentPeriod = [Current YTD]
			VAR __ValuePreviousPeriod = [PQ Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: 56c00691-4198-4cf4-be65-3944d1ceae5c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Current YTD' = ```
			
			DIVIDE ( 
			    [QOQ Current YTD],
			    [PQ Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: 9f201bdd-c3c7-45dc-aa05-782e235c294b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: 06a388f4-d3c4-418c-a663-8dbc8cec0ec8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Current YTD' =
			
			VAR __ValueCurrentPeriod = [Current YTD]
			VAR __ValuePreviousPeriod = [PM Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: 73183078-707c-44dd-aa7d-10396ae327a8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Current YTD' = ```
			
			DIVIDE ( 
			    [MOM Current YTD],
			    [PM Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Current YTD
		lineageTag: 48b6df9a-e0b5-4f80-8bf2-982003c643fc

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Current YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: 13d3f768-273c-474c-8cd5-e4d49d07fdf8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Current YTD' =
			
			VAR __ValueCurrentPeriod = [YTD Current YTD]
			VAR __ValuePreviousPeriod = [PYTD Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: fa0ed440-7e42-4d01-94a9-8d7315523e9d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Current YTD' = ```
			
			DIVIDE ( 
			    [YOYTD Current YTD],
			    [PYTD Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: a7272e14-19b7-45be-9f14-f3f5d181a855

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Current YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: 3c1e062f-5269-44c9-9b52-9215315f4799

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Current YTD' =
			
			VAR __ValueCurrentPeriod = [QTD Current YTD]
			VAR __ValuePreviousPeriod = [PQTD Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: f17a591e-b585-4f56-8485-bb6616163388

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Current YTD' = ```
			
			DIVIDE ( 
			    [QOQTD Current YTD],
			    [PQTD Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: 12ecbf40-5c83-49f6-952e-7b2faee62e5f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Current YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: 8ecaf30b-d426-4c60-b4e2-fb489e1218ca

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Current YTD' =
			
			VAR __ValueCurrentPeriod = [MTD Current YTD]
			VAR __ValuePreviousPeriod = [PMTD Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: 3f04549d-32e1-4746-9b3a-b474606ffffd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Current YTD' = ```
			
			DIVIDE ( 
			    [MOMTD Current YTD],
			    [PMTD Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Current YTD
		lineageTag: 72fa2e20-c811-4530-9df5-6034e156f8d6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: e5650778-c5ae-43bb-9d53-0801c24798e7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Current YTD' =
			
			VAR __ValueCurrentPeriod = [YTD Current YTD]
			VAR __ValuePreviousPeriod = [PYC Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: b6f3c341-947b-4231-af81-adf1f8325090

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Current YTD' = ```
			
			DIVIDE ( 
			    [YTDOPY Current YTD],
			    [PYC Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: ef0e8e87-d926-47a5-a579-8a53fc2c6524

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: f0a9ed2e-a427-4aa1-b4f7-c81ff54b3d49

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Current YTD' =
			
			VAR __ValueCurrentPeriod = [QTD Current YTD]
			VAR __ValuePreviousPeriod = [PQC Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: 1cd76f2e-917e-43c1-8ce4-7c10de0eedf3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Current YTD' = ```
			
			DIVIDE ( 
			    [QTDOPQ Current YTD],
			    [PQC Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: 74403d37-8ad1-4b64-b2f5-f57f8653054e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: 19630b47-3481-40b0-b069-034ad7834cb9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Current YTD' =
			
			VAR __ValueCurrentPeriod = [MTD Current YTD]
			VAR __ValuePreviousPeriod = [PMC Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: a96a3d47-f442-43e5-b080-151c2aac6dc8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Current YTD' = ```
			
			DIVIDE ( 
			    [MTDOPM Current YTD],
			    [PMC Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Current YTD
		lineageTag: 5a894480-da5f-4274-8c11-40c2737e47a9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Current YTD],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current YTD
		lineageTag: b68a2562-08cb-4ecb-85d0-860cec0039e0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Current YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Current YTD],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current YTD
		lineageTag: 92dc11f2-2590-4124-b7f6-e279c99b697d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Current YTD' =
			
			VAR __ValueCurrentPeriod = [MAT Current YTD]
			VAR __ValuePreviousPeriod = [PYMAT Current YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current YTD
		lineageTag: a51f0530-4f26-4d0a-a838-8d3ddf2c4356

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Current YTD' = ```
			
			DIVIDE ( 
			    [MATG Current YTD],
			    [PYMAT Current YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Current YTD
		lineageTag: b3219f19-1c66-4eb3-acb0-ff9eb835611d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous MTD
		lineageTag: 0ee9ba3f-1c09-43ef-b806-0ce2b69f9a14

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous MTD
		lineageTag: 8c637373-3002-4731-8e82-6fa575a14104

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous MTD
		lineageTag: 79eafb25-b50d-4af6-a94c-75232e048590

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: d3dff904-184f-428f-af54-b47b770379fe

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Previous MTD' =
			
			VAR __ValueCurrentPeriod = [Previous MTD]
			VAR __ValuePreviousPeriod = [PY Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: 8b5f8321-c3a3-46c2-bc61-4178f1c5ff23

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Previous MTD' = ```
			
			DIVIDE ( 
			    [YOY Previous MTD],
			    [PY Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: 4cc1fed7-1526-4709-a2f1-7376cf35ea9b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: 822f1901-aeac-43a0-a4f0-313fe451411d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Previous MTD' =
			
			VAR __ValueCurrentPeriod = [Previous MTD]
			VAR __ValuePreviousPeriod = [PQ Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: 2cee9b09-a91a-4738-8149-a9f419acbab4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Previous MTD' = ```
			
			DIVIDE ( 
			    [QOQ Previous MTD],
			    [PQ Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: 90db03f7-b61c-482f-b9ba-f33bc16827be

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: 3f996a5e-39c0-48df-8362-a21ed087eeaa

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Previous MTD' =
			
			VAR __ValueCurrentPeriod = [Previous MTD]
			VAR __ValuePreviousPeriod = [PM Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: 578f3b9f-ebff-46ce-b7bc-69c693cb9b6e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Previous MTD' = ```
			
			DIVIDE ( 
			    [MOM Previous MTD],
			    [PM Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous MTD
		lineageTag: f63c0244-4f1e-42a6-82a6-ba9de266c9ca

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Previous MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: 683d0713-6701-4d75-bc3a-6a78c894bea7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Previous MTD' =
			
			VAR __ValueCurrentPeriod = [YTD Previous MTD]
			VAR __ValuePreviousPeriod = [PYTD Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: 3b18c922-5ede-44a5-99a1-af1ec5be086f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Previous MTD' = ```
			
			DIVIDE ( 
			    [YOYTD Previous MTD],
			    [PYTD Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: 13a4075c-d019-49c2-b453-25e5c31c537f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Previous MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: 22c8a9fd-d3cf-49d6-9071-97da6208e7e3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Previous MTD' =
			
			VAR __ValueCurrentPeriod = [QTD Previous MTD]
			VAR __ValuePreviousPeriod = [PQTD Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: fb2a368e-cc62-44ff-82da-d54dc8e136ad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Previous MTD' = ```
			
			DIVIDE ( 
			    [QOQTD Previous MTD],
			    [PQTD Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: 0f4294af-8fb8-476b-9db2-83840cfcb95a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Previous MTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: bb64d4ee-02a5-43c8-993c-f13d3b5ec7d7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Previous MTD' =
			
			VAR __ValueCurrentPeriod = [MTD Previous MTD]
			VAR __ValuePreviousPeriod = [PMTD Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: 7f893f82-29f8-4244-972c-a179cfd5e2a3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Previous MTD' = ```
			
			DIVIDE ( 
			    [MOMTD Previous MTD],
			    [PMTD Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous MTD
		lineageTag: aeb6952f-9ca8-4b7c-9123-2136ec590510

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: ac93c2e0-bf0f-4eef-a655-b0198ef0bc0c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Previous MTD' =
			
			VAR __ValueCurrentPeriod = [YTD Previous MTD]
			VAR __ValuePreviousPeriod = [PYC Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: 311c950c-d460-4f2c-b3a3-a17b4befa3b0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Previous MTD' = ```
			
			DIVIDE ( 
			    [YTDOPY Previous MTD],
			    [PYC Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: acd9dca8-c87f-4cc2-b4fd-0d99b78909fc

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: c9660fca-c844-4bad-b6db-3072957d1634

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Previous MTD' =
			
			VAR __ValueCurrentPeriod = [QTD Previous MTD]
			VAR __ValuePreviousPeriod = [PQC Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: 11967711-1257-4901-a92f-0f373ce0ba81

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Previous MTD' = ```
			
			DIVIDE ( 
			    [QTDOPQ Previous MTD],
			    [PQC Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: 778726ba-748c-4fcc-a4da-637277edf8bb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: 7ea5f32b-6916-4a8b-a5a7-31dbb7b74f25

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Previous MTD' =
			
			VAR __ValueCurrentPeriod = [MTD Previous MTD]
			VAR __ValuePreviousPeriod = [PMC Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: 24dda74a-2edf-46a1-b2b8-c60929b5b87a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Previous MTD' = ```
			
			DIVIDE ( 
			    [MTDOPM Previous MTD],
			    [PMC Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous MTD
		lineageTag: 791c9652-e24c-4410-be58-18b87790c9e0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous MTD],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous MTD
		lineageTag: dbb69266-c934-4a4e-ad2b-f768cb5a70aa

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Previous MTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Previous MTD],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous MTD
		lineageTag: 1b99f7c3-47e7-42b9-bebd-adf5efcc89d6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Previous MTD' =
			
			VAR __ValueCurrentPeriod = [MAT Previous MTD]
			VAR __ValuePreviousPeriod = [PYMAT Previous MTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous MTD
		lineageTag: 023022c9-dc0a-48b0-8fdd-8afb7b34ca8a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Previous MTD' = ```
			
			DIVIDE ( 
			    [MATG Previous MTD],
			    [PYMAT Previous MTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous MTD
		lineageTag: 1fed5fd4-6b16-44bb-ae5e-b80e15aa683b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous QTD
		lineageTag: 9cf67111-d215-4ca9-bcda-4b63a8690380

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous QTD
		lineageTag: 21d56de9-1ce0-48ee-a676-5db05b61f62e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous QTD
		lineageTag: 4d857799-7bb5-4d54-ba22-120077cbc14c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: e609b294-bdb2-4890-bf9c-21ee6a0ba353

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Previous QTD' =
			
			VAR __ValueCurrentPeriod = [Previous QTD]
			VAR __ValuePreviousPeriod = [PY Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: bef2a603-8c23-464f-8f63-7bbd3c4c1fa0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Previous QTD' = ```
			
			DIVIDE ( 
			    [YOY Previous QTD],
			    [PY Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: 1cc12191-f20f-45e2-beee-71eb1b63aeae

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: 151ba7f6-5b9a-462f-924e-82ae776d9328

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Previous QTD' =
			
			VAR __ValueCurrentPeriod = [Previous QTD]
			VAR __ValuePreviousPeriod = [PQ Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: e4c7783d-f110-49e6-a491-c59563c750ef

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Previous QTD' = ```
			
			DIVIDE ( 
			    [QOQ Previous QTD],
			    [PQ Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: ccb34148-19a9-42ac-8ef5-ee3734d651c8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: 0dbde95f-8540-46ab-8234-589fe18a788f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Previous QTD' =
			
			VAR __ValueCurrentPeriod = [Previous QTD]
			VAR __ValuePreviousPeriod = [PM Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: 177dcc7e-9733-4ff2-9ea3-cbe17218c8cf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Previous QTD' = ```
			
			DIVIDE ( 
			    [MOM Previous QTD],
			    [PM Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous QTD
		lineageTag: 7673ee2f-55d2-48ee-aaa5-d496ce12818c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Previous QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: fc476d8a-c091-441d-bb29-7dbb3f7b527d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Previous QTD' =
			
			VAR __ValueCurrentPeriod = [YTD Previous QTD]
			VAR __ValuePreviousPeriod = [PYTD Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: de447698-99f1-4e3b-8e26-2bb3f18a097c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Previous QTD' = ```
			
			DIVIDE ( 
			    [YOYTD Previous QTD],
			    [PYTD Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: dad0be31-1774-4d15-a189-6d3445fce6ba

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Previous QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: 0f6b0f6b-79a4-4a88-9f54-0c42636d9e26

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Previous QTD' =
			
			VAR __ValueCurrentPeriod = [QTD Previous QTD]
			VAR __ValuePreviousPeriod = [PQTD Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: c7978b32-7a59-4f2c-96b7-b35c10081d06

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Previous QTD' = ```
			
			DIVIDE ( 
			    [QOQTD Previous QTD],
			    [PQTD Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: 491f39a6-0427-4ff1-8f24-30d6f362f195

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Previous QTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: 96e57f9d-8457-4fb1-abdd-3414e30f4cba

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Previous QTD' =
			
			VAR __ValueCurrentPeriod = [MTD Previous QTD]
			VAR __ValuePreviousPeriod = [PMTD Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: 8f4544d2-757e-4e79-b77e-a8bf9836de98

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Previous QTD' = ```
			
			DIVIDE ( 
			    [MOMTD Previous QTD],
			    [PMTD Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous QTD
		lineageTag: b240e736-cd85-4bf4-b8a8-73dbb4caacaf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: d5d57960-837e-4049-b7fb-e065a0a2c603

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Previous QTD' =
			
			VAR __ValueCurrentPeriod = [YTD Previous QTD]
			VAR __ValuePreviousPeriod = [PYC Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: f26404ea-7be8-428d-8c7c-ff5da72f60a5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Previous QTD' = ```
			
			DIVIDE ( 
			    [YTDOPY Previous QTD],
			    [PYC Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: b4158dba-d865-4894-a2a0-e02cf569ce04

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: afc0587e-a147-468c-a1ea-80f7f5de8cfb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Previous QTD' =
			
			VAR __ValueCurrentPeriod = [QTD Previous QTD]
			VAR __ValuePreviousPeriod = [PQC Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: 25a30955-5366-481f-b184-b96dbefedfb0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Previous QTD' = ```
			
			DIVIDE ( 
			    [QTDOPQ Previous QTD],
			    [PQC Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: eb568656-a207-47a4-99c6-f82693de19e7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: 4d86247a-410c-4ed5-be7b-8ae090c748e2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Previous QTD' =
			
			VAR __ValueCurrentPeriod = [MTD Previous QTD]
			VAR __ValuePreviousPeriod = [PMC Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: af6fda0c-70fc-4cf5-9ab9-a9ce4b4ab899

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Previous QTD' = ```
			
			DIVIDE ( 
			    [MTDOPM Previous QTD],
			    [PMC Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous QTD
		lineageTag: bcc1ba6e-d41c-4e7c-b82a-16bac37711c8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous QTD],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous QTD
		lineageTag: fce94c65-b3c6-491d-82b6-30dc34049d0b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Previous QTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Previous QTD],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous QTD
		lineageTag: 5d6f830a-4ad8-4c9a-83e4-fe562e7377e2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Previous QTD' =
			
			VAR __ValueCurrentPeriod = [MAT Previous QTD]
			VAR __ValuePreviousPeriod = [PYMAT Previous QTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous QTD
		lineageTag: 13b10922-d5a3-4766-9932-c123e0c41ba8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Previous QTD' = ```
			
			DIVIDE ( 
			    [MATG Previous QTD],
			    [PYMAT Previous QTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous QTD
		lineageTag: 73ec8710-0c30-41c9-b51c-00b171b901c3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous YTD
		lineageTag: 880574d7-603e-4445-9024-66548b1270da

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous YTD
		lineageTag: 45248dcc-6503-43ad-b81f-8fe153532fc9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Time Intelligence\Previous YTD
		lineageTag: 58794c8b-4815-4637-87d3-3faec6ca35f4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: d8414103-7369-47a6-b869-d558348e9a12

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Previous YTD' =
			
			VAR __ValueCurrentPeriod = [Previous YTD]
			VAR __ValuePreviousPeriod = [PY Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: c4df2ea0-1571-46fb-a2df-74daefbf7fad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Previous YTD' = ```
			
			DIVIDE ( 
			    [YOY Previous YTD],
			    [PY Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: 2a3e367f-bd67-4848-8fad-02d23c262339

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: a171d191-6f02-4d5a-8033-af7df9c52fd7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Previous YTD' =
			
			VAR __ValueCurrentPeriod = [Previous YTD]
			VAR __ValuePreviousPeriod = [PQ Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: 749d08d7-e286-47c1-acf1-bd3c75aa772c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Previous YTD' = ```
			
			DIVIDE ( 
			    [QOQ Previous YTD],
			    [PQ Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: 0f1ccb8a-72bc-49a9-8e03-f4c130769e8b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: 94bf9825-07f5-45d4-99d5-aaf82225a3bd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Previous YTD' =
			
			VAR __ValueCurrentPeriod = [Previous YTD]
			VAR __ValuePreviousPeriod = [PM Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: c0fef041-568c-48cc-89ff-16c0a38de75a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Previous YTD' = ```
			
			DIVIDE ( 
			    [MOM Previous YTD],
			    [PM Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\Previous YTD
		lineageTag: 13b53c68-ee90-476b-9e53-2a06bb462a53

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Previous YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: ae8df5e3-c32c-46d6-a573-04f67d9d112f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Previous YTD' =
			
			VAR __ValueCurrentPeriod = [YTD Previous YTD]
			VAR __ValuePreviousPeriod = [PYTD Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: d8cd24fd-05ac-46f4-9499-0d47155d4abb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Previous YTD' = ```
			
			DIVIDE ( 
			    [YOYTD Previous YTD],
			    [PYTD Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: af49ecb4-0694-4152-9beb-e90115cbbc2e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Previous YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: bb94824d-d13b-4084-84e3-7bc458e6da83

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Previous YTD' =
			
			VAR __ValueCurrentPeriod = [QTD Previous YTD]
			VAR __ValuePreviousPeriod = [PQTD Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: 5ced5c71-f3e7-4f20-a109-0689ff536b99

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Previous YTD' = ```
			
			DIVIDE ( 
			    [QOQTD Previous YTD],
			    [PQTD Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: 20110d4b-7c65-4eab-8096-755edaf7756f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Previous YTD],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: a9c49c82-aa0f-4e01-82f9-27f1fb236627

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Previous YTD' =
			
			VAR __ValueCurrentPeriod = [MTD Previous YTD]
			VAR __ValuePreviousPeriod = [PMTD Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: a97eed07-f27b-43d7-be40-9c8870c2e92b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Previous YTD' = ```
			
			DIVIDE ( 
			    [MOMTD Previous YTD],
			    [PMTD Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\Previous YTD
		lineageTag: 45a1cf5d-f7f8-4594-99f9-21ddd635898e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: c23d7084-2976-4bde-9868-e0690b24c44f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Previous YTD' =
			
			VAR __ValueCurrentPeriod = [YTD Previous YTD]
			VAR __ValuePreviousPeriod = [PYC Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: fa6e5ba8-c078-4dd2-967b-015c906d7016

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Previous YTD' = ```
			
			DIVIDE ( 
			    [YTDOPY Previous YTD],
			    [PYC Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: 52e483bb-9c81-42ba-8e36-33429069b9f7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: b8b7f480-13b1-495b-8db9-a03d0788aff5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Previous YTD' =
			
			VAR __ValueCurrentPeriod = [QTD Previous YTD]
			VAR __ValuePreviousPeriod = [PQC Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: 97e85607-18b4-4541-bb82-7caffb091672

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Previous YTD' = ```
			
			DIVIDE ( 
			    [QTDOPQ Previous YTD],
			    [PQC Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: 8c2e0615-1b9a-49b1-8bc3-d3b8af1daeb6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: 3f0c2bb0-1c4c-4762-9563-8c4adc8b293c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Previous YTD' =
			
			VAR __ValueCurrentPeriod = [MTD Previous YTD]
			VAR __ValuePreviousPeriod = [PMC Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: 6390ef25-5e8e-4cc6-a95b-994ca98b9236

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Previous YTD' = ```
			
			DIVIDE ( 
			    [MTDOPM Previous YTD],
			    [PMC Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\Previous YTD
		lineageTag: 15e94f69-0efa-4645-9b27-a50f479645ed

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Previous YTD],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous YTD
		lineageTag: 2a7ae1c3-46ab-4b43-abee-4d00158cfa93

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Previous YTD' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Previous YTD],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous YTD
		lineageTag: 4288b3fa-240c-4e90-86f4-5bc1fff6d316

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Previous YTD' =
			
			VAR __ValueCurrentPeriod = [MAT Previous YTD]
			VAR __ValuePreviousPeriod = [PYMAT Previous YTD]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous YTD
		lineageTag: fee5e6d2-f7a2-45a1-a302-d405c5709d00

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Previous YTD' = ```
			
			DIVIDE ( 
			    [MATG Previous YTD],
			    [PYMAT Previous YTD]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\Previous YTD
		lineageTag: 98802b0d-829f-4081-8ef2-fdfcd10421e9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\MOM Growth
		lineageTag: 65d77a52-c652-45ff-83d7-6764b3a2840d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\MOM Growth
		lineageTag: e4856786-5d91-432c-b807-ac647bcea4c5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\MOM Growth
		lineageTag: e265e0dc-a956-4c32-bd6c-3174b5ae3d2a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: 8f029b14-2321-4f74-89c4-02a186f1cb47

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY MOM Growth' =
			
			VAR __ValueCurrentPeriod = [MOM Growth]
			VAR __ValuePreviousPeriod = [PY MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: 16b5ceba-cde1-4fcd-b9bf-3fd584d2c08b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % MOM Growth' = ```
			
			DIVIDE ( 
			    [YOY MOM Growth],
			    [PY MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: c84df4ac-fc45-46a4-880d-6719bb1e2e62

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: ac771b57-f163-412b-b3b3-5982b686920f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ MOM Growth' =
			
			VAR __ValueCurrentPeriod = [MOM Growth]
			VAR __ValuePreviousPeriod = [PQ MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: 05d018fa-43cb-4230-b5f7-620a12ce4e11

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % MOM Growth' = ```
			
			DIVIDE ( 
			    [QOQ MOM Growth],
			    [PQ MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: 5c922cd9-5353-40aa-af18-54bf7870857a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: 3c0326bd-c262-48ea-8029-4753224ccdb7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM MOM Growth' =
			
			VAR __ValueCurrentPeriod = [MOM Growth]
			VAR __ValuePreviousPeriod = [PM MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: e86e552b-6972-45ca-b24f-738db0574960

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % MOM Growth' = ```
			
			DIVIDE ( 
			    [MOM MOM Growth],
			    [PM MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\MOM Growth
		lineageTag: 8c96168d-686e-4b03-bacd-482576e736bd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD MOM Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: ba483a13-b40e-42a7-a0bf-77640a0ad394

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD MOM Growth' =
			
			VAR __ValueCurrentPeriod = [YTD MOM Growth]
			VAR __ValuePreviousPeriod = [PYTD MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: 8872b2c8-ad42-4a92-806b-d54d977f41b5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % MOM Growth' = ```
			
			DIVIDE ( 
			    [YOYTD MOM Growth],
			    [PYTD MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: 7f6347e1-ae6d-4e1c-96c3-68e94cb919af

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD MOM Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: 8ac2a888-964d-4155-8d16-bb5c23fbb011

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD MOM Growth' =
			
			VAR __ValueCurrentPeriod = [QTD MOM Growth]
			VAR __ValuePreviousPeriod = [PQTD MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: d475cb17-8f6b-4854-8780-bcdfbec73876

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % MOM Growth' = ```
			
			DIVIDE ( 
			    [QOQTD MOM Growth],
			    [PQTD MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: 1196ffb7-6f3c-4f0d-809f-891442fc2b23

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD MOM Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: 70c69c97-97fa-4ea1-b2ce-087052880666

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD MOM Growth' =
			
			VAR __ValueCurrentPeriod = [MTD MOM Growth]
			VAR __ValuePreviousPeriod = [PMTD MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: b02a5e13-6bb4-49ff-8717-c1ed874197ef

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % MOM Growth' = ```
			
			DIVIDE ( 
			    [MOMTD MOM Growth],
			    [PMTD MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\MOM Growth
		lineageTag: 1a0c9d77-7fa3-4c08-b769-f45dd80183bf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: e1e3ddcf-ed41-4833-999f-cfc1302f1c3a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY MOM Growth' =
			
			VAR __ValueCurrentPeriod = [YTD MOM Growth]
			VAR __ValuePreviousPeriod = [PYC MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: 7942e5dc-c6dd-40c8-ab85-14abd2c03b6d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % MOM Growth' = ```
			
			DIVIDE ( 
			    [YTDOPY MOM Growth],
			    [PYC MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: d4bec924-999a-4fad-8b2a-27bad67547ae

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: 79c004f0-fe7c-4e5f-af72-fc2f374fa8a5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ MOM Growth' =
			
			VAR __ValueCurrentPeriod = [QTD MOM Growth]
			VAR __ValuePreviousPeriod = [PQC MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: b44f012c-fbd0-406d-8a4b-3174f6caf9c3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % MOM Growth' = ```
			
			DIVIDE ( 
			    [QTDOPQ MOM Growth],
			    [PQC MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: afa9b9de-2146-44b3-a34f-26fa4ae95b90

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: 8f96b3bf-4ab1-4ffa-a612-21c3c387d833

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM MOM Growth' =
			
			VAR __ValueCurrentPeriod = [MTD MOM Growth]
			VAR __ValuePreviousPeriod = [PMC MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: 8a55da6b-3a1a-4c5e-b4fa-684f9e424d45

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % MOM Growth' = ```
			
			DIVIDE ( 
			    [MTDOPM MOM Growth],
			    [PMC MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\MOM Growth
		lineageTag: 5b2ddbb3-c5c2-43ab-98e9-8494dfb55f6c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MOM Growth],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\MOM Growth
		lineageTag: c434caa7-dbd8-43af-9274-f5a82411706b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT MOM Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT MOM Growth],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\MOM Growth
		lineageTag: 708aede5-99de-4db6-90e5-6d85bda77598

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG MOM Growth' =
			
			VAR __ValueCurrentPeriod = [MAT MOM Growth]
			VAR __ValuePreviousPeriod = [PYMAT MOM Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\MOM Growth
		lineageTag: 37347bc1-180c-41ef-b4cb-aed65ebf186d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % MOM Growth' = ```
			
			DIVIDE ( 
			    [MATG MOM Growth],
			    [PYMAT MOM Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\MOM Growth
		lineageTag: 9fdd9436-f199-4428-853a-a7bff1a7ab29

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\QOQ Growth
		lineageTag: 0216ea49-8cc4-4366-980d-fbf685cab768

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\QOQ Growth
		lineageTag: 48faea2a-4a75-428c-ab82-765e2f14a175

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\QOQ Growth
		lineageTag: c2e040e4-b6a8-4930-9705-b292744a2aad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: 1815062a-d498-47b8-b007-1f431ee527c7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [QOQ Growth]
			VAR __ValuePreviousPeriod = [PY QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: be74b639-a443-480a-aa2d-f84e7ca80575

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % QOQ Growth' = ```
			
			DIVIDE ( 
			    [YOY QOQ Growth],
			    [PY QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: 4e9f4066-01bd-4a11-b17e-40d7a81810d9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: e08ec4b2-f22b-46ee-ad04-8188f59d2149

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [QOQ Growth]
			VAR __ValuePreviousPeriod = [PQ QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: 08cf3426-3334-41e5-ac60-4d38eb1a1be8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % QOQ Growth' = ```
			
			DIVIDE ( 
			    [QOQ QOQ Growth],
			    [PQ QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: 054b7702-1259-4ade-9a6e-2cafd4d582ee

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: e549e232-0019-4c7c-b46f-092c3b43c89a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [QOQ Growth]
			VAR __ValuePreviousPeriod = [PM QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: fa50eb6d-805b-4919-9f57-511e42bcee60

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % QOQ Growth' = ```
			
			DIVIDE ( 
			    [MOM QOQ Growth],
			    [PM QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\QOQ Growth
		lineageTag: f6a1e55b-d4bb-4486-a2a6-ec0ad424e4d2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD QOQ Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 8ed4a32a-4764-42c4-83bc-087b8ae9754c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [YTD QOQ Growth]
			VAR __ValuePreviousPeriod = [PYTD QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 1f56e8fa-e318-43ea-b069-79e17a514bef

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % QOQ Growth' = ```
			
			DIVIDE ( 
			    [YOYTD QOQ Growth],
			    [PYTD QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 6eff653f-129e-4bf6-b917-ec4336962e09

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD QOQ Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: e8178f76-7da1-4b3f-959d-70bb36a0785f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [QTD QOQ Growth]
			VAR __ValuePreviousPeriod = [PQTD QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 0f18f580-fb9d-4d04-98a7-11054e544940

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % QOQ Growth' = ```
			
			DIVIDE ( 
			    [QOQTD QOQ Growth],
			    [PQTD QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 7c11e29f-00c8-4e65-9e19-de61251d3186

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD QOQ Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 7708a8bd-e775-4937-bdb7-10a70aa282db

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [MTD QOQ Growth]
			VAR __ValuePreviousPeriod = [PMTD QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 4a5cae66-f8bf-4482-8d03-4b1da6a17384

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % QOQ Growth' = ```
			
			DIVIDE ( 
			    [MOMTD QOQ Growth],
			    [PMTD QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\QOQ Growth
		lineageTag: 3749b26f-c0a4-4720-9a41-f0a9008f25d8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: 1c5b1d04-9691-43ee-8b7c-4eedda0510bc

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [YTD QOQ Growth]
			VAR __ValuePreviousPeriod = [PYC QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: 862a3607-c215-4c2c-b7b2-e21b0b201e80

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % QOQ Growth' = ```
			
			DIVIDE ( 
			    [YTDOPY QOQ Growth],
			    [PYC QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: bfde56d3-7ccb-4e34-9c88-da385076755b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: d5522150-1805-4dcc-bad3-d19388b2efb4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [QTD QOQ Growth]
			VAR __ValuePreviousPeriod = [PQC QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: ff744944-5c04-4e36-aed8-2fa00561be89

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % QOQ Growth' = ```
			
			DIVIDE ( 
			    [QTDOPQ QOQ Growth],
			    [PQC QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: 792c19e4-b3ca-47cb-b0c4-400770dd90f2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: 5f393abe-c255-478f-bd76-df230e96ed68

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [MTD QOQ Growth]
			VAR __ValuePreviousPeriod = [PMC QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: cd77c185-5ee1-4fd0-b46d-a2b219108498

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % QOQ Growth' = ```
			
			DIVIDE ( 
			    [MTDOPM QOQ Growth],
			    [PMC QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\QOQ Growth
		lineageTag: 76ef5408-9ae0-4e6a-b8ef-d4659aef433c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QOQ Growth],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\QOQ Growth
		lineageTag: 495136d6-02f2-4a7a-b7ba-7137919bb555

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT QOQ Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT QOQ Growth],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\QOQ Growth
		lineageTag: ff4ba18d-b600-4034-913f-7dc2282cf63e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG QOQ Growth' =
			
			VAR __ValueCurrentPeriod = [MAT QOQ Growth]
			VAR __ValuePreviousPeriod = [PYMAT QOQ Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\QOQ Growth
		lineageTag: 3e440b01-2d3c-4ef2-9bcb-8b0816f7af83

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % QOQ Growth' = ```
			
			DIVIDE ( 
			    [MATG QOQ Growth],
			    [PYMAT QOQ Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\QOQ Growth
		lineageTag: affd99de-fd71-4826-ae56-30ada30c4f62

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        DATESYTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\YOY Growth
		lineageTag: 266a768b-da4b-42d3-80e3-47a486e09826

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        DATESQTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\YOY Growth
		lineageTag: 22c6fcde-231c-4cf3-a086-e7c246a9a58b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        DATESMTD ( 'Calender'[Date] )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date total\Time Intelligence\YOY Growth
		lineageTag: d6f89957-09ac-49e9-9363-afd560a9b1d1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: 1d36d0b1-cc74-40f2-b2ca-f4ff65078b99

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY YOY Growth' =
			
			VAR __ValueCurrentPeriod = [YOY Growth]
			VAR __ValuePreviousPeriod = [PY YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: f7527574-5c97-4fde-9539-55622b2a90e9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % YOY Growth' = ```
			
			DIVIDE ( 
			    [YOY YOY Growth],
			    [PY YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: 4435b18b-795c-4357-8bab-8f32bc6e45d8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: cc591500-d3f1-470a-bf85-601d0bde54e8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ YOY Growth' =
			
			VAR __ValueCurrentPeriod = [YOY Growth]
			VAR __ValuePreviousPeriod = [PQ YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: 3d82b6cf-31e8-4a61-ab70-edc4d0fc7099

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % YOY Growth' = ```
			
			DIVIDE ( 
			    [QOQ YOY Growth],
			    [PQ YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: 416a9bfe-417c-4818-814b-4e53944ea740

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: 9552173f-83c7-4226-9f75-d6cf73b87082

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM YOY Growth' =
			
			VAR __ValueCurrentPeriod = [YOY Growth]
			VAR __ValuePreviousPeriod = [PM YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: 6537d365-8e07-406c-823b-dafa58580d17

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % YOY Growth' = ```
			
			DIVIDE ( 
			    [MOM YOY Growth],
			    [PM YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Time Intelligence\YOY Growth
		lineageTag: dce73b31-d2c0-4159-af68-345c3aa71cad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD YOY Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, YEAR ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: 88e46332-cfcd-437d-ab9d-e8d248934379

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD YOY Growth' =
			
			VAR __ValueCurrentPeriod = [YTD YOY Growth]
			VAR __ValuePreviousPeriod = [PYTD YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: 17b77822-f96b-4fcf-ad9a-c2b0fa88c91d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % YOY Growth' = ```
			
			DIVIDE ( 
			    [YOYTD YOY Growth],
			    [PYTD YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: 523933d8-6d71-443c-8f1a-99491fe1936e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD YOY Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, QUARTER ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: f909a20e-872e-4a12-8073-74a87a647610

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD YOY Growth' =
			
			VAR __ValueCurrentPeriod = [QTD YOY Growth]
			VAR __ValuePreviousPeriod = [PQTD YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: 2a1ad9a3-9e91-423e-96f5-5c7e820874e9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % YOY Growth' = ```
			
			DIVIDE ( 
			    [QOQTD YOY Growth],
			    [PQTD YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: 29953230-5217-4ff0-9d83-ad84e8da4a77

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD YOY Growth],
			        CALCULATETABLE (
			            DATEADD ( 'Calender'[Date], -1, MONTH ),
			            'Calender'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: b168ffb7-cd49-4928-b624-2b9f296b819b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD YOY Growth' =
			
			VAR __ValueCurrentPeriod = [MTD YOY Growth]
			VAR __ValuePreviousPeriod = [PMTD YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: 7e04bde9-71b7-478e-852a-4baa2597ee52

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % YOY Growth' = ```
			
			DIVIDE ( 
			    [MOMTD YOY Growth],
			    [PMTD YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Time Intelligence\YOY Growth
		lineageTag: 2c5483bc-d96b-4f70-9f26-10f86d5f745a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: 09007f42-9f98-4372-ab50-76f187b077cd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY YOY Growth' =
			
			VAR __ValueCurrentPeriod = [YTD YOY Growth]
			VAR __ValuePreviousPeriod = [PYC YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: ba32d32a-db60-4676-aba5-4bd876c74b11

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % YOY Growth' = ```
			
			DIVIDE ( 
			    [YTDOPY YOY Growth],
			    [PYC YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: 1c86e941-8a35-49a1-b907-b886ef7fc82e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, QUARTER )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: bda555f7-7674-40c8-83a0-9b5b7168fc41

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ YOY Growth' =
			
			VAR __ValueCurrentPeriod = [QTD YOY Growth]
			VAR __ValuePreviousPeriod = [PQC YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: 64a688ef-d262-4fb2-9dc7-95b4bc5bfbd7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % YOY Growth' = ```
			
			DIVIDE ( 
			    [QTDOPQ YOY Growth],
			    [PQC YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: 73bcfcfe-f066-4732-8f0c-17b39a3f678c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        PARALLELPERIOD ( 'Calender'[Date], -1, MONTH )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: 6b18ac74-1153-4197-9ff1-f08fe69f18e0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM YOY Growth' =
			
			VAR __ValueCurrentPeriod = [MTD YOY Growth]
			VAR __ValuePreviousPeriod = [PMC YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: 93968731-b731-4eef-978a-8c0cfeae2eab

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % YOY Growth' = ```
			
			DIVIDE ( 
			    [MTDOPM YOY Growth],
			    [PMC YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Time Intelligence\YOY Growth
		lineageTag: c1ee71bd-33b9-4dd4-b2d8-43e361b24b00

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YOY Growth],
			        DATESINPERIOD (
			            'Calender'[Date],
			            MAX ( 'Calender'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\YOY Growth
		lineageTag: 3eb898b3-42bd-4739-b1f5-02ddc64612c7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT YOY Growth' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT YOY Growth],
			        DATEADD ( 'Calender'[Date], -1, YEAR )
			    )
			)
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\YOY Growth
		lineageTag: ceddbbd8-c7a2-431d-b4bd-b65c7b42e9ed

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG YOY Growth' =
			
			VAR __ValueCurrentPeriod = [MAT YOY Growth]
			VAR __ValuePreviousPeriod = [PYMAT YOY Growth]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0%;-0%;0%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\YOY Growth
		lineageTag: c38df7ae-a9a3-429d-9dff-aaf873622dc5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % YOY Growth' = ```
			
			DIVIDE ( 
			    [MATG YOY Growth],
			    [PYMAT YOY Growth]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Time Intelligence\YOY Growth
		lineageTag: d7b4edfd-daf1-417d-a249-0d0854a60fe0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column SP_ID
		dataType: string
		lineageTag: 51bc01b2-3831-4e61-a22b-e3094b61b808
		summarizeBy: none
		sourceColumn: SP_ID

		annotation SummarizationSetBy = Automatic

	column Geo_ID
		dataType: string
		lineageTag: b30978d3-8bed-4e41-b5d8-506e2fc64f71
		summarizeBy: none
		sourceColumn: Geo_ID

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		lineageTag: 46780b02-ec1b-4e47-958d-dbf614550243
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 426fb7a4-4076-440b-ac79-e576b576e9c6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 64395ca3-c94b-4a49-9b62-15ebabadb767
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Customers
		dataType: int64
		formatString: 0
		lineageTag: ecfec014-b61f-42c4-a361-0ff7b8e1eba7
		summarizeBy: sum
		sourceColumn: Customers

		annotation SummarizationSetBy = Automatic

	column Boxes
		dataType: int64
		formatString: 0
		lineageTag: 6e9e69c1-d709-432d-912a-fdeb7efa2880
		summarizeBy: sum
		sourceColumn: Boxes

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
				    Source = Sql.Databases("LISHA\SQLEXPRESS"),
				    ac = Source{[Name="ac"]}[Data],
				    dbo_sales = ac{[Schema="dbo",Item="sales"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_sales,{{"Product", "Product_ID"}, {"Sales_Person", "SP_ID"}, {"Geo", "Geo_ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

